site_name: Java VTL

site_url: https://statisticsnorway.github.io/java-vtl/
repo_url: https://github.com/statisticsnorway/java-vtl
edit_uri: edit/develop/java-vtl-documentation/docs

theme_dir: cinder
pages:
- Home: index.md
- Reference: reference.md
- Playground: playground.md

extra_css:
    - 'https://unpkg.com/codemirror@5.23.0/lib/codemirror.css'
    - css/railroad-diagrams.css
    - css/railroad-vtl.css

extra_javascript:
    - js/main.js

google_analytics: ['UA-85245041-1', 'auto']

